spring.application.name=attendance_tracker_be
server.port = 8081
app.jwt.secret=mySuperSecretKeyForAttendanceTracker123456789
spring.mongodb.uri=mongodb+srv://deyg2453_db_user:g1o2u3r4a5b6@clustergourab.5kre7na.mongodb.net/attendance_tracker?retryWrites=true&w=majority&appName=ClusterGourab